Repository bcgov/NRPTI, pull requests merged in 2023-11, with the labels that each got.

#1162 [HOTFIX][NRPTI-1161]** Hotfix to import all mines from core
  api/src/integrations/core/datasource.js
Labels: Backend

#1159 [CHORE]/[NRPTI-1158]
  angular/projects/common/src/app/utils/record-constants.ts
  angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.html
  angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.ts
Labels: Frontend

#1164 [BUGFIX][NRPTI-1163] - Enforcement Actions Issue Fix
  angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions-resolver.ts
  angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
  angular/projects/common/src/app/utils/record-constants.ts
Labels: Frontend

#1170 [TECH-DEBT][NRPTI-1167] Agency Update Angular Test
  angular/projects/admin-nrpti/src/app/agencies/agencies.component.spec.ts
Labels: Frontend

#1168 [TECH-DEBT][NRPTI-1167]** Imports test coverage improvements
  api/src/importers/alc/base-record-utils.test.js
  api/src/importers/alc/datasource.test.js
  api/src/importers/ams/datasource.test.js
  api/src/importers/cmdb/datasource.test.js
  api/src/importers/coors/base-record-utils.test.js
  api/src/importers/coors/datasource.test.js
  api/src/importers/era/datasource.test.js
  api/src/importers/flnr/datasource.test.js
  api/src/importers/mis/datasource.test.js
Labels: Backend

#1174 [TECH-DEBT][NRPTI-1167]** add additional testing for CORE integration
  api/src/integrations/core-documents/datasource.test.js
  api/src/integrations/core/collection-utils.test.js
  api/src/integrations/core/datasource.test.js
  api/src/integrations/core/mine-utils.test.js
  api/src/integrations/core/permit-utils.test.js
Labels: Backend

#1176 [TECH-DEBT][NRPTI-1167]** add additional testing for EPIC integration
  api/src/integrations/bcogc/administrative-penalties-utils.test.js
  api/src/integrations/bcogc/orders-utils.test.js
  api/src/integrations/bcogc/warnings-utils.test.js
  api/src/integrations/epic/base-record-utils.test.js
  api/src/integrations/epic/certificates-amendment-utils.test.js
  api/src/integrations/epic/certificates-utils.test.js
  api/src/integrations/epic/epic-record-type-enum.js
  api/src/integrations/epic/epic-record-type-enum.test.js
  api/src/integrations/epic/epic-utils.test.js
  api/src/integrations/epic/inspections-utils.test.js
  api/src/integrations/epic/orders-other-utils.test.js
  api/src/integrations/epic/orders-utils.test.js
Labels: Backend

#1177 [TECH-DEBT][NRPTI-1167]** add additional testing for NRIS integrations
  api/package.json
  api/src/integrations/nris-emli/datasource.test.js
  api/src/integrations/nris-epd/datasource.test.js
  api/test/setEnvVars.js
Labels: Backend, Testing

#1178 [BUGFIX][NRPTI-1173]** Fix CSV export bug to reference the correct agency name
  angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.spec.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend
