Repository bcgov/NRPTI, pull requests merged in 2023-10, with the labels that each got.

#1118 [NRPTI-1115] DEV FEATURE** Create Dockerfiles and docker-compose
  api/Dockerfile
  docker-compose.yaml
  mongoSeed/init/create-db.js
Labels: Backend, Docker

#1123 [NRPTI-1112] Add outcome description values to CSV outputs in NRCED
  angular/projects/public-nrpti/src/app/records/utils/record-utils.spec.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend

#1121 [NRPTI-1045] TESTS** Fix broken tests in API
  api/package-lock.json
  api/package.json
  api/src/controllers/collection-controller.js
  api/src/controllers/post/inspection.js
  api/src/controllers/search.js
  api/src/importers/alc/utils/csv-utils.test.js
  api/src/importers/coors/court-conviction-utils.js
  api/src/importers/coors/court-conviction-utils.test.js
  api/src/importers/coors/utils/csv-utils.js
  api/src/importers/coors/utils/csv-utils.test.js
  api/test/factories/factory_helper.js
  api/test/tests/controllers/map-info-controller.test.js
  api/test/tests/controllers/search.test.js
Labels: Backend, Testing

#1124 [NRPTI-1097] BUG: Fix location field in COORS court conviction importer
  api/src/importers/coors/court-conviction-utils.js
  api/src/importers/coors/court-conviction-utils.test.js
Labels: Backend

#1127 [NRPTI-1113] FEAT: Add summary to GTYJ enforcement outcome imports
  api/src/importers/coors/court-conviction-utils.js
  api/src/importers/coors/court-conviction-utils.test.js
Labels: Backend

#1130 [NRPTI-1045] FIX** update Authorized Publish Agencies / Fix Tests
  api/src/importers/coors/court-conviction-utils.test.js
  api/src/utils/constants/misc.js
Labels: Backend

#1140 [NRPTI-1138] HOTFIX** Update NRCED homepage to new agency codes
  angular/projects/admin-nrpti/src/app/home/home.component.ts
  angular/projects/public-nrpti/src/app/home/home.component.html
  angular/projects/public-nrpti/src/app/home/home.component.spec.ts
  angular/projects/public-nrpti/src/app/home/home.component.ts
Labels: Frontend

#1143 [NRPTI-1142] HOTFIX** Revert optional chaining due to old version of node
  api/src/controllers/collection-controller.js
  api/src/controllers/post/inspection.js
  api/src/controllers/search.js
  api/src/importers/coors/court-conviction-utils.js
Labels: Backend

#1157 FIX/NRPTI-1156
  angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.spec.ts
  angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.ts
  angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts
  angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.spec.ts
  angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.ts
Labels: Frontend
