Repository bcgov/NRPTI, pull requests merged in 2024-02, with the labels that each got.

#1190 [TECH-DEBT][NRPTI-#1182] - Update READMEs for NRPTI
  README.md
  angular/README.md
  angular/projects/common/src/app/search-filter-template/readme.md
  angular/projects/global/README.md
  api/README.md
  api/src/models/README.md
  api/src/models/bcmi/README.md
  docs/README.md
  tools/README.md
Labels: Backend, Frontend, Docs

#1192 [TASK][NRPTI-#1185] Fix Typos in HTML. Update Migration README and database.json-sample files.
  angular/projects/admin-nrpti/src/app/agencies/agencies.component.ts
  angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions.component.html
  angular/projects/admin-nrpti/src/app/header/header.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts
  angular/projects/common/src/app/link-add-edit/link-add-edit.component.html
  angular/projects/public-nrpti/src/app/header/header.component.html
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
  angular/projects/public-nrpti/src/index.html
  api/database.json-sample
  api/migrations/README.md
Labels: Backend, Frontend

#1193 [FEATURE]{NRPTI-#1179] Update BCOGC importer and filters to reflect new act title
  angular/projects/common/src/app/utils/record-constants.ts
  angular/projects/public-lng/src/app/faq/faq.component.html
  api/src/integrations/bcogc/administrative-penalties-utils.js
  api/src/integrations/bcogc/administrative-penalties-utils.test.js
  api/src/integrations/bcogc/inspections-utils.js
  api/src/integrations/bcogc/inspections-utils.test.js
  api/src/integrations/bcogc/orders-utils.js
  api/src/integrations/bcogc/orders-utils.test.js
  api/src/integrations/bcogc/utils/csv-utils.js
  api/src/integrations/bcogc/utils/csv-utils.test.js
Labels: Backend, Frontend

#1198 [FIX][NRPTI-#1146] - Update NRIS-EPD integration to give admin:env-epd role, add migration to update existing NRIS-EPD records
  api/migrations/20240216204922-adminEnvEpdToNrisEpdRecords.js
  api/src/controllers/post/inspection.js
  api/src/controllers/post/inspection.spec.js
Labels: Backend

#1199 [FIX][NRPTI-#1103] - Remove all "Fish and Seafood Act" Inspections from Collection
  api/migrations/20240226205826-removeErroneousFishAndSeafoodActRecords.js
Labels: Backend

#1200 DRAFT [NRPTI-1191] FEATURE** autofocus param searches for specific record
  angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
  angular/projects/public-nrpti/src/app/services/factory.service.ts
Labels: Frontend
