Repository bcgov/NRPTI, pull requests merged in 2024-06, with the labels that each got.

#1234 [BUG][NRPTI-1231] Fix bug where manually added records are not appearing in the nrced csv export
  angular/projects/admin-nrpti/src/app/records/records-resolver.spec.ts
  angular/projects/admin-nrpti/src/app/records/records-resolver.ts
  angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
  api/src/controllers/acts-regulations-controller.js
  api/src/controllers/search.js
Labels: Backend, Frontend

#1236 [BUG][NRPTI-1235] Check legislation act codes during CSV export
  angular/projects/admin-nrpti/src/app/records/records-resolver.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend

#1238 [FEATURE][NRPTI-1125] Automated publishing of redacted mines act inspection reports
  api/src/integrations/nris-emli/datasource.js
  api/src/integrations/nris-emli/datasource.test.js
  api/test/setEnvVars.js
Labels: Backend, Testing

#1243 [BUG][NRPTI-1233] Amalgamated permits not showing in BCMI
  .github/ISSUE_TEMPLATE/bug.md
  angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts
  angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.ts
  angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
  angular/projects/common/src/app/utils/record-constants.ts
  api/migrations/20240619192233-updateBCMICollectionTypeField.js
  api/src/controllers/mine-controller.js
  api/src/integrations/core/datasource.js
  api/src/integrations/core/permit-utils.js
  api/src/models/bcmi/permit-bcmi.js
  api/src/models/master/permit.js
Labels: Backend, Frontend

#1244 [FIX][NRPTI-1233] updated bcmi collection migration to properly find all relevant permits
  api/migrations/20240619192233-updateBCMICollectionTypeField.js
Labels: Backend

#1248 [BUG][NRPTI-1242] Add support for creating & updating permits from multiple permit codes
  api/src/integrations/core/datasource.js
  api/src/integrations/core/datasource.test.js
  api/src/integrations/core/permit-utils.js
  api/src/integrations/core/permit-utils.test.js
Labels: Backend

#1247 [BUG][NRPTI-1165] token refresh for core importer
  api/migrations/20240619192233-updateBCMICollectionTypeField.js
  api/src/integrations/core-documents/datasource.js
  api/src/integrations/core/datasource.js
  api/src/integrations/integration-utils.js
  tools/README.md
Labels: Backend

#1249 [BUG][NRPTI-1242] add support for mx permits - bug fix
  api/src/controllers/search.js
  api/src/integrations/core/datasource.js
  api/src/integrations/core/mine-utils.js
Labels: Backend
