Repository bcgov/NRPTI, pull requests merged in 2024-04, with the labels that each got.

#1196 Feat/[NRPTI-1194] - Move hardcoded Acts and Regulations to DB
  angular/projects/admin-nrpti/src/app/agencies/agencies.component.spec.ts
  angular/projects/admin-nrpti/src/app/app.module.ts
  angular/projects/admin-nrpti/src/app/import/import.component.ts
  angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html
  angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html
  angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
  angular/projects/admin-nrpti/src/app/services/acts.service.ts
  angular/projects/admin-nrpti/src/app/services/factory.service.ts
  angular/projects/common/src/app/legislation/legislation-add-edit/legislation-add-edit.component.spec.ts
  angular/projects/common/src/app/legislation/legislation-add-edit/legislation-add-edit.component.ts
  angular/projects/common/src/app/legislation/legislation-list-add-edit/legislation-list-add-edit.component.spec.ts
  angular/projects/common/src/app/utils/record-constants.ts
  angular/projects/global/src/lib/services/config.service.ts
  angular/projects/global/src/lib/utils/act-data-service-nrced.ts
  angular/projects/global/src/lib/utils/act-data-service-nrpti.ts
  angular/projects/public-lng/src/app/faq/faq.component.html
  angular/projects/public-nrpti/src/app/app.module.ts
  angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.spec.ts
  angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.ts
  angular/projects/public-nrpti/src/app/services/acts.service.ts
  angular/projects/public-nrpti/src/app/services/factory.service.ts
  api/migrations/20240304222852-createAllActsRegulationsMapping.js
  api/migrations/20240306211156-updateRecordsOilandGasAct.js
  api/openshift/cron.yaml
  api/src/controllers/acts-regulations-controller.js
  api/src/integrations/bcogc/administrative-penalties-utils.js
  api/src/integrations/bcogc/administrative-penalties-utils.test.js
  api/src/integrations/bcogc/datasource.js
  api/src/integrations/bcogc/inspections-utils.js
  api/src/integrations/bcogc/inspections-utils.test.js
  api/src/integrations/bcogc/orders-utils.js
  api/src/integrations/bcogc/orders-utils.test.js
  api/src/swagger/swagger.yaml
  api/src/utils/constants/legislation-code-map.js
  api/src/utils/constants/record-type-enum.js
  mongoSeed/init/create-db.js
Labels: Backend, Frontend, OpenShift

#1221 [BUG-FIX][NRPTI-1219] - Permissions not working as expected
  angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.ts
  angular/projects/admin-nrpti/src/app/services/factory.service.ts
  angular/projects/common/src/app/legislation/legislation-add-edit/legislation-add-edit.component.spec.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
Labels: Frontend

#1220 [CHANGE][NRPTI#1211] Add intermediate code for act name
  angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-detail/annual-report-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-detail/certificate-amendments-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/certificates/certificate-detail/certificate-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-detail/correspondence-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-detail/dam-safety-inspection-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/permits/permit-detail/permit-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/records-resolver.spec.ts
  angular/projects/admin-nrpti/src/app/records/records-resolver.ts
  angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/reports/report-detail/report-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/self-reports/self-report-detail/self-report-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.ts
  angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
  angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.ts
  angular/projects/admin-nrpti/src/app/services/acts.service.ts
  angular/projects/common/src/app/legislation/legislation-list-detail-admin/legislation-list-detail.component.ts
  angular/projects/common/src/app/legislation/legislation-list-detail-public/legislation-list-detail.component.ts
  angular/projects/common/src/app/utils/utils.ts
  angular/projects/global/src/lib/utils/act-data-service-nrced.ts
  angular/projects/global/src/lib/utils/act-data-service-nrpti.ts
  angular/projects/public-nrpti/src/app/services/acts.service.ts
  api/README.md
  api/migrations/20240402191551-modifyRecordsEnergyResourceActivitiesActCode.js
  api/src/controllers/acts-regulations-controller.js
Labels: Backend, Frontend

#1222 [CHANGE][NRPTI#1211][cont'd] add intermediate code for act name
  angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/records-resolver.spec.ts
  angular/projects/admin-nrpti/src/app/records/records-resolver.ts
  angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
  angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
  angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
  angular/projects/global/src/lib/utils/act-data-service-nrced.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend

#1224 [BUG][NRPTI-1219b] Fix for Edit being disabled for authorized users
  angular/projects/admin-nrpti/src/app/records/utils/record-component.ts
Labels: Frontend
