Repository bcgov/NRPTI, pull requests merged in 2025-05, with the labels that each got.

#1312 CI: updated Docker to work with Keycloak
  angular/Dockerfile
  angular/Dockerfile-public-nrpti
  angular/entrypoint-public-nrpti.sh
  angular/entrypoint.sh
  angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
  docker-compose.yaml
Labels: Frontend, Docker

#1313 ci: added pr open workflow
  .github/workflows/deploy.yml
  .github/workflows/pr-open.yml
  tools/angular-on-nginx/admin-nrced.dc.yaml
  tools/angular-on-nginx/public-nrced.dc.yaml
  tools/api/api.dc.yaml
  tools/metabase/postgres.dc.yaml
Labels: GitHub Actions

#1321 ci: added webhook trigger
  .github/workflows/deploy.yml
  .github/workflows/pr-open.yml
  angular/package-lock.json
  tools/angular-builder/angular-builder.bc.yaml
  tools/api/api.bc.yaml
Labels: Frontend, GitHub Actions

#1322 feat: added csv feature for testing
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
Labels: Frontend

#1330 fix: logging to see export issue
  angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
  angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
  angular/projects/public-nrpti/src/app/services/factory.service.ts
Labels: Frontend

#1332 fix: Test to fix export
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend

#1333 chore: Remove comments used for debugging
  angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
Labels: Frontend
